-- Add Folio column to tickets for auto-incrementing friendly ID
-- We use BIGINT GENERATED BY DEFAULT AS IDENTITY starting at 1001 for a nice start

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'tickets' AND column_name = 'folio') THEN
        ALTER TABLE public.tickets 
        ADD COLUMN folio BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001 INCREMENT BY 1);
    END IF;
END $$;
